//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 11:47:25 AM CEST 
//


package com.xebia.representation;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for rels.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rels">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="rels/book"/>
 *     &lt;enumeration value="rels/price"/>
 *     &lt;enumeration value="rels/payment"/>
 *     &lt;enumeration value="rels/related"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum Rels {

    @XmlEnumValue("rels/book")
    RELS_BOOK("rels/book"),
    @XmlEnumValue("rels/price")
    RELS_PRICE("rels/price"),
    @XmlEnumValue("rels/payment")
    RELS_PAYMENT("rels/payment"),
    @XmlEnumValue("rels/related")
    RELS_RELATED("rels/related");
    private final String value;

    Rels(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Rels fromValue(String v) {
        for (Rels c: Rels.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
